In [1]:
'''
here I try to get the gradient of a cnn
Teng Li
24.11.2021
'''
import torch
import torch.nn as nn
import torch.nn.functional as f
# input
x = torch.rand([1,1,4,4])
x.requires_grad_()
print(x)
# target
y = torch.tensor([0])
print(y)
#loss function
loss_func = nn.NLLLoss()

tensor([[[[0.7911, 0.8758, 0.1104, 0.1205],
          [0.8092, 0.5409, 0.6832, 0.2473],
          [0.4817, 0.0541, 0.2431, 0.5817],
          [0.2159, 0.9328, 0.3239, 0.4082]]]], requires_grad=True)
tensor([0])


In [2]:
#conv layers
conv1 = nn.Conv2d(1,3,(2,4)) #(1,1,4,4)->(1,3,3,1)
#fc layers
fc1 = nn.Linear(9,2)

In [3]:
out = conv1(x)
print('after conv:',out)
print(out.req)
out = out.view(1,-1)
print('after reshape:',out)
out = fc1(out)
print('after fc:',out)
y_hat = f.log_softmax(out,dim=1)
print('y_hat:',y_hat)
loss = loss_func(y_hat,y)
print('loss:',loss)

after conv: tensor([[[[ 0.0072],
          [ 0.3788],
          [ 0.2685]],

         [[ 0.1580],
          [ 0.1107],
          [ 0.0498]],

         [[-0.1238],
          [ 0.3206],
          [ 0.2333]]]], grad_fn=<MkldnnConvolutionBackward>)
after reshape: tensor([[ 0.0072,  0.3788,  0.2685,  0.1580,  0.1107,  0.0498, -0.1238,  0.3206,
          0.2333]], grad_fn=<ViewBackward>)
after fc: tensor([[ 0.1423, -0.4534]], grad_fn=<AddmmBackward>)
y_hat: tensor([[-0.4390, -1.0347]], grad_fn=<LogSoftmaxBackward>)
loss: tensor(0.4390, grad_fn=<NllLossBackward>)


In [4]:
gradient = torch.autograd.grad(loss,x)
print(gradient)


(tensor([[[[-0.0247,  0.0290, -0.0290, -0.0380],
          [ 0.0051,  0.1221, -0.1030,  0.0166],
          [ 0.0200,  0.0196,  0.0317, -0.0091],
          [-0.0979, -0.0485,  0.0700, -0.0687]]]]),)
