In [1]:
'''
This is a practice of saving and reloading Net
Teng Li
07.10.2021
'''

'\nThis is a practice of saving and reloading Net\nTeng Li\n07.10.2021\n'

In [11]:
import torch
import torch.nn as nn

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu") # use GPU if available
# Firstly build a Net as example
class Net(nn.Module):
     def __init__(self):#init the module
        super().__init__()
        #Conv layers
        self.fc = nn.Linear(3,2)
    
     def forward(self,x):
        out = self.fc(x)
        return out


In [12]:
#init Net
net = Net().to(DEVICE)
#show weights
for p in net.parameters():
    print(p)

Parameter containing:
tensor([[-0.3526,  0.4220, -0.0125],
        [ 0.2452,  0.1754, -0.4690]], requires_grad=True)
Parameter containing:
tensor([0.0134, 0.0091], requires_grad=True)


In [20]:
# save net 
torch.save(net,'net.pkl')
# or save net's state
torch.save(net.state_dict(),'net_state.pkl')

/home/teng/anaconda3/lib/python3.7/site-packages/torch/serialization.py:402: UserWarning: Couldn't retrieve source code for container of type Net. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "


In [21]:
# now reload net
# reload from 'net.pkl'
if torch.cuda.is_available():
    net_new = torch.load('net.pkl').cuda()
else:
    net_new = torch.load('net.pkl')
# show weights
for p in net_new.parameters():
    print(p)

Parameter containing:
tensor([[-0.3526,  0.4220, -0.0125],
        [ 0.2452,  0.1754, -0.4690]], requires_grad=True)
Parameter containing:
tensor([0.0134, 0.0091], requires_grad=True)


In [23]:
# or reload from 'net_state.pkl'
net_new1.load_state_dict(torch.load('net_state.pkl'))
# show weights
for p in net_new1.parameters():
    print(p)

Parameter containing:
tensor([[-0.3526,  0.4220, -0.0125],
        [ 0.2452,  0.1754, -0.4690]], requires_grad=True)
Parameter containing:
tensor([0.0134, 0.0091], requires_grad=True)
